version: "3.10"
services:

  frontend:  # Frontend-часть
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      - api
#      - bot

  api:  # Backend-часть
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      test:
        condition: service_completed_successfully
    volumes:
      - ./:/api

  test:  # Тесты
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: pytest

#  ЭТОТ КОНТЕЙНЕР ОТКЛЮЧЕН, Т.К. НА УДАЛЁННОМ СЕРВЕРЕ ОН УЖЕ ЗАПУЩЕН
#  bot:  # Бот Телеграм
#    build:
#      context: .
#    depends_on:
#      postgres:
#        condition: service_healthy
#      migrations:
#        condition: service_completed_successfully
#    command: python manage.py runbot
#    restart: on-failure
#    volumes:
#      - ./:/api

  migrations:  # Миграции
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  postgres:  # БД PostgreSQL
    image: postgres:latest
    ports:
      - ${PORT}:${PORT}
    user: ${USER}
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    volumes:
      # Для сохранения информации в БД
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", -U postgres]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:  # Для БД
